"""add_llm_provider_to_jobs

Revision ID: 6f75f293120d
Revises: 83155e5177e4
Create Date: 2026-08-02 17:31:56.786679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f75f293120d'
down_revision: Union[str, Sequence[str], None] = '83155e5177e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('llm_provider', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'llm_provider')
    # ### end Alembic commands ###
