"""add_langfuse_trace_id_to_jobs

Revision ID: 83155e5177e4
Revises: 196413974a5d
Create Date: 2026-07-31 19:45:05.366478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83155e5177e4'
down_revision: Union[str, Sequence[str], None] = '196413974a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('langfuse_trace_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'langfuse_trace_id')
    # ### end Alembic commands ###
